[package]
name = "rust-experiments"
version = "0.1.0"
authors = ["Maciej Gorywoda <makingthematrix@gmail.com>"]

[dependencies]
rand = "0.3"
im = "9.0.0"

[dev-dependencies]
quickcheck = "0.6.0"
spectral = "0.6.0"
criterion = "0.1.2"

[[bench]]
name = "criterion_tests"
harness = false